<?php

return [
    'term_of_use' => ['en' => 'Term of use', 'sw' => 'term of use'],
    'privacy_policy' => ['en' => 'Privacy Policy', 'sw' => 'Privacy Policy'],
    'announcement' => ['en' => 'Announcements', 'sw' => 'Matangazo'],
    'news' => ['en' => 'News', 'sw' => 'Habari'],
    'recently_events' => ['en' => 'Recently Events', 'sw' => 'Matukio ya Karibuni'],
    'view_all_events' => ['en' => 'View All Events', 'sw' => 'Matukio Zaidi'],
    'view_all_announcement' => ['en' => 'View All Announcement', 'sw' => 'Matangazo Zaidi'],
    'read_more' => ['en' => 'Read More', 'sw' => 'Soma Zaidi'],
    'view_all' => ['en' => 'View All', 'sw' => 'Angalia Zaidi'],
    'More' => ['en' => 'More', 'sw' => 'Zaidi'],
    'more_videos' => ['en' => 'More Videos', 'sw' => 'Video nyingine'],
    'video_now_playing' => ['en' => 'Now Playing', 'sw' => 'Inayocheza'],
    'search' => ['en' => 'Search', 'sw' => 'Tafuta'],
    'read' => ['en' => 'Read', 'sw' => 'Soma'],
    'videos' => ['en' => 'Videos', 'sw' => 'Video'],
    'campus_life' => ['en' => 'Campus Life', 'sw' => 'Maisha ya Chuo'],
    'find_programe' => ['en' => 'Find Programe', 'sw' => 'Tafuta Kozi'],
    'enter_keyword' => ['en' => 'Enter Keyword', 'sw' => 'Weka Neno'],
    'select' => ['en' => 'Select', 'sw' => 'chegua'],
    'undergraduate' => ['en' => 'Undergraduate', 'sw' => 'Shahada ya Kwanza'],
    'postgraduate' => ['en' => 'Postgraduate', 'sw' => 'Shahada ya Uzamili'],
    'non_degree' => ['en' => 'Non-Degree', 'sw' => 'Yasiyo ya shahada'],
    'home' => ['en' => 'Home', 'sw' => 'Mwanzo'],
    'page' => ['en' => 'page', 'sw' => 'Kurasa'],
    'other_pages' => ['en' => 'Other Pages', 'sw' => 'Kurasa Nyingine'],
    'study' => ['en' => 'Study', 'sw' => 'Soma'],
    'programme' => ['en' => 'Programme', 'sw' => 'Kozi'],
    'find_programme' => ['en' => 'Find Programme', 'sw' => 'Tafuta Kozi'],
    'search_keyword' => ['en' => 'Search Keyword', 'sw' => 'Weka neno'],
    'AZ_course_list' => ['en' => 'A-Z Course List', 'sw' => 'A-Z, Orodha ya Kozi'],
    'Directions_to_Main_Campus' => ['en' => 'Directions to Main Campus', 'sw' => 'Jinsi ya Kufika Chuoni Kampasi Kuu'],
    'contact_us' => ['en' => 'Contanct Us', 'sw' => 'Wasiliana nasi'],
    'Contact_us_form' => ['en' => 'Contanct Us', 'sw' => 'Wasiliana nasi kupitia fomu hii'],
    'Main_campus_location' => ['en' => 'Main Campus Location on Map', 'sw' => 'Kampasi Kuu Katika Ramani'],
    'Other_campus_institutions_etc' => ['en' => 'Contact other Campuses, Colleges and University section', 'sw' => 'Wasiliana na Kampasi, Skuli na Idara nyingine za Chuo'],
    'PObox' => ['en' => 'P.O. Box', 'sw' => 'S.L.P'],
    'StreetRegion' => ['en' => 'Street/Region', 'sw' => 'Mtaa/Mkoa'],
    'PhoneNo' => ['en' => 'Phone No', 'sw' => 'Simu'],
    'Fax' => ['en' => 'Fax No', 'sw' => 'Fax No'],
    'EmailAddress' => ['en' => 'Email Address', 'sw' => 'barua pepe'],
    'email' => ['en' => 'Email', 'sw' => 'Barua pepe'],
    'Connect' => ['en' => 'Connect', 'sw' => 'Ungana Nasi'],
    'Upcoming_events' => ['en' => 'Upcoming Events', 'sw' => 'Matukio yajayo'],
    'recent_events' => ['en' => 'Recent Events', 'sw' => 'Matukio ya Hivi Karibuni'],
    'social_media' => ['en' => 'Social Media', 'sw' => 'Mitandao ya Kijamii'],
    'events' => ['en' => 'Events', 'sw' => 'Matukio Mbalimbali'],
    'news_events' => ['en' => 'News & Events', 'sw' => 'Habari na Matukio Mbalimbali'],
    'other_events' => ['en' => 'Other Events', 'sw' => 'Matukio Mengine'],
    'other_news' => ['en' => 'Other News', 'sw' => 'Habari Nyingine'],
    'other_announcement' => ['en' => 'Other Announcements', 'sw' => 'Matangazo Mengine'],
    'leadership_and_administration' => ['en' => 'Leadership & Administration', 'sw' => 'Uongozi & Utawala'],
    'annual_reports' => ['en' => 'Annual Reports', 'sw' => 'Ripoti za Mwisho wa Mwaka'],
    'aboutus' => ['en' => 'About Us', 'sw' => 'KUhusu sis'],
    'research_document' => ['en' => 'Research Documents', 'sw' => 'Utafiti'],
    'student_corner' => ['en' => 'Student Corner', 'sw' => 'kwa wanafunzi'],
    'staff_corner' => ['en' => 'Student Corner', 'sw' => 'kwa wanafunzi'],
    'staff_directory' => ['en' => 'Staff Directory', 'sw' => 'Staff Directory'],
    'postal_address' => ['en' => 'Postal Address', 'sw' => 'Sanduku la Posta'],
    'call_us' => ['en' => 'Call Us', 'sw' => 'Tupigie'],
    'department' => ['en' => 'Departments', 'sw' => 'Idara na Vitengo'],
    'quick_links' => ['en' => 'Quick Links', 'sw' => 'Kurasa Nyingine'],
];
