<?php

/*
 * Use this file t manageme url/ routes in the application  
 */
return [
    'enablePrettyUrl' => TRUE,
    'showScriptName' => TRUE,
    'enableStrictParsing' => FALSE,
    'rules' => [
        ///STUDY MENUS REOUTES
        //COLLEGES PAGES
        'colleges/<code>/programmes' => 'college/programs',
        'colleges/<code>/programs' => 'college/programs',
        'colleges/<code>/program' => 'college/programs',
        'colleges/<code>/programmes/<item>' => 'college/programs',
        'colleges/<code>/programs/<item>' => 'college/programs',
        'colleges/<code>/program/<item>' => 'college/programs',
        'colleges/<code>/news/<item>' => 'college/news',
        'colleges/<code>/news' => 'college/news',
        'colleges/<code>/events/<item>' => 'college/events',
        'colleges/<code>/events' => 'college/events',
        'colleges/<code>/announcements' => 'college/announcements',
        'colleges/<code>/announcements/<item>' => 'college/announcements',        
        'colleges/<code>/researchs/<item>' => 'college/researchs',
        //'colleges/<code>/<page>/<action>' => 'colleges/<action>',
        //'colleges/<code>/<page>' => 'colleges/page',
//        'colleges|college/<code>/<page>/<item>' => 'college/index',
//        'colleges|college/<code>/<page>/<item>/<subitem>' => 'college/index',
//        'colleges|college/<code>/<page>/<item>/<subitem>/<subitem2>' => 'college/index',
        'colleges|college/<code>' => 'college/index',
        //SCHOOLS PAGES
        'schools/<code>/programmes' => 'schools/programs',
        'schools/<code>/programs' => 'schools/programs',
        'schools/<code>/program' => 'schools/programs',
        'schools/<code>/programmes/<item>' => 'schools/programs',
        'schools/<code>/programs/<item>' => 'schools/programs',
        'schools/<code>/program/<item>' => 'schools/programs',
        'schools/<code>/news/<item>' => 'schools/news',
        'schools/<code>/news' => 'schools/news',
        'schools/<code>/events/<item>' => 'schools/events',
        'schools/<code>/events' => 'schools/events',
        'schools/<code>/announcements' => 'schools/announcements',
        'schools/<code>/announcements/<item>' => 'schools/announcements',
        'schools|school/<code>' => 'schools/index',
        //INSTITUTES PAGES
        'institutes/<code>/programmes' => 'institutes/programs',
        'institutes/<code>/programs' => 'institutes/programs',
        'institutes/<code>/program' => 'institutes/programs',
        'institutes/<code>/programmes/<item>' => 'institutes/programs',
        'institutes/<code>/programs/<item>' => 'institutes/programs',
        'institutes/<code>/program/<item>' => 'institutes/programs',
        'institutes/<code>/news/<item>' => 'institutes/news',
        'institutes/<code>/news' => 'institutes/news',
        'institutes/<code>/events/<item>' => 'institutes/events',
        'institutes/<code>/events' => 'institutes/events',
        'institutes/<code>/announcements' => 'institutes/announcements',
        'institutes/<code>/announcements/<item>' => 'institutes/announcements',
        'institutes|institute/<code>' => 'institutes/index',
        //CENTRES PAGES
        'centres/<code>/programmes' => 'centres/programs',
        'centres/<code>/programs' => 'centres/programs',
        'centres/<code>/program' => 'centres/programs',
        'centres/<code>/programmes/<item>' => 'centres/programs',
        'centres/<code>/programs/<item>' => 'centres/programs',
        'centres/<code>/program/<item>' => 'centres/programs',
        'centres/<code>/news/<item>' => 'centres/news',
        'centres/<code>/news' => 'centres/news',
        'centres/<code>/events/<item>' => 'centres/events',
        'centres/<code>/events' => 'centres/events',
        'centres/<code>/announcements' => 'centres/announcements',
        'centres/<code>/announcements/<item>' => 'centres/announcements',
        'centres|centre/<code>' => 'centres/index',
        //UNITS PAGES
        'directorates/<code>/programmes' => 'directorates/programs',
        'directorates/<code>/programs' => 'directorates/programs',
        'directorates/<code>/program' => 'directorates/programs',
        'directorates/<code>/programmes/<item>' => 'directorates/programs',
        'directorates/<code>/programs/<item>' => 'directorates/programs',
        'directorates/<code>/program/<item>' => 'directorates/programs',
        'directorates/<code>/news/<item>' => 'directorates/news',
        'directorates/<code>/news' => 'directorates/news',
        'directorates/<code>/events/<item>' => 'directorates/events',
        'directorates/<code>/events' => 'directorates/events',
        'directorates/<code>/announcements' => 'directorates/announcements',
        'directorates/<code>/announcements/<item>' => 'directorates/announcements',
        //////
        ///MAIN SITE
        'background|introduction' => 'about/index',
        'about|about-us|aboutus' => 'about/index',
        'about-us/leadership' => 'about/leadership',
        'about/leadership' => 'about/leadership',
        'about-us/annual-reports|about/annual-reports' => 'about/reports',
        'about/<category>' => 'about/index',
        'site/annual-reports' => 'about/reports',
        'site/student-corner|student-corner' => 'site/student-corner',
        'site/staff-corner|staff-corner' => 'site/staff-corner',
        //study routes
        'study/programme' => 'study/programme',
        'study/programme/<category>' => 'study/programme',
        'study/programmes' => 'study/programmes',
        'study/catalogue' => 'study/catalogue',
        'study/catalogue/<category>' => 'study/catalogue',
        'study/programmes/<category>' => 'study/programmes',
        'study/<category>/programmes' => 'study/programmes',
        'study|site/study' => 'study/index',
        'study/<category>' => 'study/index',
        ///research routes
        'research' => 'research/index',
        'research/project|research/projects' => 'research/projects',
        'research/policies|research/journals|research/books' => 'research/documents',
        'research/publications|research/publications/' => 'research/publications',
        'research/publications/<category>' => 'research/publications',
        'research/<category>' => 'research/index',
        ///public service routes
        'public-service' => 'public-service/index',
        'public-service/<category>' => 'public-service/index',
        ///public service routes
        'campus-life|site/campus-life' => 'campus-life/index',
        'campus-life/<category>' => 'campus-life/index',
        ///connects menus
        'connect/contact-us|site/contact-us' => 'site/contacts',
        'news-and-events|site/news-and-events|connect/news-and-events' => 'connect/news-and-events',
        'announcements|connect/announcements|site/announcements' => 'connect/announcements',
        'site/news|news|connect/news' => 'connect/news',
        'site/events|events|connect/events' => 'connect/events',
        'site/leadership' => 'about/leadership',
        'leadership' => 'about/leadership',
        //////
        ///BACKEND ROUTES
        'backend/templates' => 'backend/templates',
        'backend/<category>' => 'backend/<category>',
        'backend/logout' => 'backend/logout',
        'backend|login' => 'backend/login',
        'users/<category>' => 'users/<category>',
        'habari/<category>' => 'habari/<category>',
        'matukio/<category>' => 'matukio/<category>',
        'video/<category>' => 'video/<category>',
        'announcement/<category>' => 'announcement/<category>',
        'slide-shows/<category>' => 'slide-shows/<category>',
        'basic-page/<category>' => 'basic-page/<category>',
        'programmes/<category>' => 'programmes/<category>',
        'projects/<category>' => 'projects/<category>',
        'staff-list/<category>' => 'staff-list/<category>',
        'contacts/<category>' => 'contacts/<category>',
        'social-media-accounts/<category>' => 'social-media-accounts/<category>',
        'connect/social-media' => 'site/social-media',
        'contacts/<category>' => 'contacts/<category>',
        'menu/<category>' => 'menu/<category>',
        'custom-blocks/<category>' => 'custom-blocks/<category>',
        ///default route
        'language|site/language|site/language/' => '/site/language',
        '<front>' => 'site/index',
        'site/<code>' => 'site/page',
        'site/<page>' => 'site/page',
        //'site' => 'site/index',
        '/' => 'site/index',
    ///BACKEND
    ],
];
